### ISSUE TITLE
[CR] Misleading variable name

### ISSUE THREAD

**Issue by Mittelblut9** [VLCCommunity/VLCOneKey#16]
I just wanted to open a new ticket because of this line. It says 'Client **Secret'**. 
I opened the website and checked the code. But this wasn't the **Secret** instead it was the **Client ID**.

https://github.com/VLCCommunity/VLCOneKey/blob/9485e981ce87aad7e580b6acf39fbfaaa183b9a3/views/index.ejs#L40

Solution:
Change **googleSecret** to **googleClient**

Exp. from Google:
![image](https://user-images.githubusercontent.com/67608550/200842264-4a6ab0d6-8d27-4357-9902-8dab1ea5db04.png)

**Comment by RaturiAR7** [comment]
Please assign me this issue.
